branch-defaults:
  default:
    environment: backend-dev
environment-defaults:
  backend-dev:
    branch: null
    repository: null
global:
  application_name: backend
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
