# For full config options, check the docs:
#    docs.serverless.com

service: comp4442-a3

provider:
  name: aws
  runtime: nodejs12.x

functions:
  generateSummary:
    handler: handler.generateSummary
    iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
            - '/*'

#    Define function environment variables here
#    environment:
#      variable2: value2

plugins:
  - serverless-offline
